version: "3.8"

services:
  db:
    image: postgres:15
    container_name: grocery_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grocerydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: grocery_api
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/grocerydb"
      PORT: 5000
      JWT_SECRET: "questionpro_assignment"

volumes:
  pg_data:
